### ISSUE TITLE
Stealth: Server Refactor

### ISSUE THREAD

**Issue by cookiengineer** [cookiengineer/stealth-browser#73]
Multicast DNS Integration requires a better structure for the `stealth/source/Server.mjs` - as it's currently very hacky on how the lookahead procedure is implemented to understand multiple network protocols generically.

This is dependent on the WS Protocol Refactor (which needs a separate WS Packet Parser). All other Packet Parsers have been implemented already and are working.

Implement the following Composites (that can be spawned `n` times on different ports):

- [x] `stealth/source/server/Proxy.mjs` that handles only `SOCKS` proxied connections. See #74 
- [x] `stealth/source/server/Webproxy.mjs` that handles `CONNECT` HTTP/S requests and the `/stealth/` proxy namespace (for the webview and iframe).
- [x] `stealth/source/server/Webserver.mjs` that handles static assets; and nothing more.
- [x] `stealth/source/server/Service.mjs` that handles all `WS` connections and API requests. See #72
- [x] `stealth/source/server/Compeer.mjs` that handles all Multicast DNS and DNS-SD integrations and workflows. See #61 for details.

**Comment by cookiengineer** [comment]
New Reviews that have to be created in order to end-to-end test the Server Modules:

- [x] stealth/server/Proxy
- [x] stealth/server/Webproxy
- [x] stealth/server/Webserver
- [x] stealth/server/Services
- [x] stealth/server/Router
- [x] stealth/packet/DNS
- [x] stealth/packet/HTTP
- [x] stealth/packet/SOCKS
- [x] stealth/packet/WS

**Comment by cookiengineer** [comment]
As of https://github.com/tholian-network/stealth/commit/e49d605d61961352ec7cdfe61cb0b0270cd877be all the remaining reviews and tests have been implemented.
